name: Discord Notification
on:
  push:
    branches: [main]

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Notify on Discord
        uses: fateyan/action-discord-notifier@v1
        with:
          message-title: New Commit Pushed
          webhook: ${{ secrets.DISCORD_WEBHOOKS }}